from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.models.claim import Claim
from app.auth_utils import get_current_user
from app.routes.summary import build_underwriting_intelligence

router = APIRouter(prefix="/renewal", tags=["Renewal"])


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@router.get("/memo")
def renewal_memo(
    policy_number: str | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    query = db.query(Claim).filter(
        Claim.organization_id == current_user["organization_id"]
    )

    if policy_number:
        query = query.filter(Claim.policy_number == policy_number)

    claims = query.all()

    intelligence = build_underwriting_intelligence(claims)

    total_claims = len(claims)
    open_claims = len([c for c in claims if c.status == "Open"])
    litigation_claims = len([c for c in claims if c.litigation])

    top_claims = sorted(
        claims,
        key=lambda c: float(c.total_incurred or 0),
        reverse=True,
    )[:5]

    top_claim_text = "\n".join(
        [
            f"- {c.claim_number} | {c.line_of_business} | ${float(c.total_incurred or 0):,.0f}"
            for c in top_claims
        ]
    )

    memo = f"""
LOSSQ AI RENEWAL MEMO
Selected Policy: {policy_number or "All Policies"}

----------------------------------------

ACCOUNT OVERVIEW

Risk Level: {intelligence["risk_level"]}
Renewal Risk: {intelligence["renewal_risk"]}
Risk Score: {intelligence["risk_score"]}
Submission Strength: {intelligence["submission_strength"]}

----------------------------------------

CLAIM SUMMARY

Total Claims: {total_claims}
Open Claims: {open_claims}
Litigation Claims: {litigation_claims}

Total Incurred:
${intelligence["metrics"]["total_incurred"]:,.2f}

----------------------------------------

TOP SEVERITY CLAIMS

{top_claim_text or "No claims available."}

----------------------------------------

UNDERWRITING SUMMARY

{intelligence["summary"]}

----------------------------------------

BROKER RECOMMENDATION

{intelligence["recommendation"]}

----------------------------------------

CARRIER NARRATIVE

{intelligence["carrier_narrative"]}

----------------------------------------

Generated by LossQ AI
"""

    return {
        "memo": memo,
        "policy_number": policy_number,
        "claims_used": total_claims,
    }